apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-dec7-baran
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet-dec7-baran
    spec:
      containers:
      - name: dotnet-dec7-baran
        image: adityaregistry.azurecr.io/dotnet-dec7_barandevops:#{Build.BuildId}#
        ports:
        - name: baran-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-dec7-baran
spec:
  ports:
  - port: 8888
    nodePort: 31011
    targetPort: baran-port
    protocol: TCP
  selector:
    app: dotnet-dec7-baran
  type: LoadBalancer
